server:
  port: 8088
  servlet:
    session:
      timeout: 120
spring:
  application:
    name: stu_emp_ms
  mvc:
  servlet:
    multipart:
      max-file-size: 5MB
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///stu_emp
    username: root
    password: 3333

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl